# config.yaml
input_file: '../data/CERRA.nc'
input_times_freq: 3 #in hours
Coeff_file: '../data/Chebyshev_Coefficnents.nc'
input_variables:
  - 10ws
  - 100ws
  - 100alpha
  - 975ws
  - 950ws
  - 975wsgrad
  - 950wsgrad
  - t2m
  - skt
  - t_975
  - t_950
  - 2mtempgrad
  - 975tempgrad
  - 950tempgrad

target_variables: [0,1,2,3,4]

train_locations: [0,1,2,3,4,5,6,7,9]

nEns: 10
tabnet_param_file : '../CI2024/tabnet_params_12th_set.csv'

test_dates_range:
  - '2017-03-24T00:00:00'
  - '2018-04-11T23:00:00'

test_locations: [10]

experiment: 'CERRA_to_CERRA'

profiles_file: